<a href="https://colab.research.google.com/github/akurtle/NLP_-_DeepLearning/blob/main/Aritficial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [80]:
df = pd.read_csv("Churn_Modelling.csv")

In [81]:
X = df.iloc[:,3:-1].values

y = df.iloc[:,-1].values

In [82]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X[:,2] = le.fit_transform(X[:,2])

In [83]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

#Doing one hot encoding to replace strings with binary

ct = ColumnTransformer(transformers=[(('encoder',OneHotEncoder(),[1]))],remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [84]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [85]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=0)

In [86]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [87]:
ann = tf.keras.models.Sequential() #Initialising an artificial neural network

In [88]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) #Creating input layer

In [89]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu")) #Adding hidden layers

In [90]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid")) #Creating output layer

In [91]:
ann.compile(optimizer="adam" , loss='binary_crossentropy',metrics=['accuracy'])

In [92]:
ann.fit(X_train,y_train,batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5808 - accuracy: 0.7526
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4719 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4362 - accuracy: 0.7981
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4238 - accuracy: 0.8139
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4162 - accuracy: 0.8175
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4085 - accuracy: 0.8224
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4012 - accuracy: 0.8261
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3942 - accuracy: 0.8288
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3882 - accuracy: 0.8335
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3828 - accura

In [94]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5) #Dont forget to check scaling

1/1 [==============================] - 0s 204ms/step
[[False]]


In [96]:
y_pred= ann.predict(X_test)
y_pred = (y_pred>0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [97]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1515   80]
 [ 194  211]]


0.863